#!/usr/bin/env bash
# Generate a basic zsh completion from a command's --help / man output.
# Scope: detect short/long option lines and emit an _arguments stub.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/utils.sh"

show_help() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] <command>

Generate a generic zsh completion for <command> by parsing its help output.

Options:
    --source FILE    Read help text from FILE instead of running the command
    --stdout         Write completion to stdout instead of dirs.src/generic
    -h, --help       Show this help
EOF
}

# Strip ANSI escape sequences. Reads stdin, writes stdout.
strip_ansi() {
    sed -E $'s/\x1B\\[[0-9;]*[A-Za-z]//g'
}

# Get raw help text for a command. Tries `--help`, then `-h`, then man.
get_help_text() {
    local cmd="$1" out
    if out=$("$cmd" --help 2>&1) && [[ -n "$out" ]]; then
        printf '%s\n' "$out"
        return 0
    fi
    if out=$("$cmd" -h 2>&1) && [[ -n "$out" ]]; then
        printf '%s\n' "$out"
        return 0
    fi
    if command_exists man && out=$(man "$cmd" 2>/dev/null | col -bx) && [[ -n "$out" ]]; then
        printf '%s\n' "$out"
        return 0
    fi
    return 1
}

# Parse option lines and emit one TSV row per option:
#   short<TAB>long<TAB>arg<TAB>desc
parse_options() {
    awk -F '' '
    function trim(s) { sub(/^[ \t]+/,"",s); sub(/[ \t]+$/,"",s); return s }
    {
        line = $0
        short = ""; long_opt = ""; arg = ""; desc = ""
        # Pattern: "  -x, --long[=ARG]   description"
        if (match(line, /^[ \t]*-[A-Za-z0-9][ \t]*,[ \t]*--[A-Za-z][A-Za-z0-9_-]*(=[A-Z_]+)?[ \t][ \t]+/)) {
            head = substr(line, 1, RLENGTH)
            desc = substr(line, RLENGTH + 1)
            if (match(head, /-[A-Za-z0-9]/)) short = substr(head, RSTART, 2)
            if (match(head, /--[A-Za-z][A-Za-z0-9_-]*/)) {
                long_opt = substr(head, RSTART, RLENGTH)
            }
            if (match(head, /=[A-Z_]+/)) arg = substr(head, RSTART + 1, RLENGTH - 1)
            print short "\t" long_opt "\t" arg "\t" trim(desc)
            next
        }
        # Pattern: "  --long[=ARG]   description"
        if (match(line, /^[ \t]*--[A-Za-z][A-Za-z0-9_-]*(=[A-Z_]+)?[ \t][ \t]+/)) {
            head = substr(line, 1, RLENGTH)
            desc = substr(line, RLENGTH + 1)
            if (match(head, /--[A-Za-z][A-Za-z0-9_-]*/)) {
                long_opt = substr(head, RSTART, RLENGTH)
            }
            if (match(head, /=[A-Z_]+/)) arg = substr(head, RSTART + 1, RLENGTH - 1)
            print "\t" long_opt "\t" arg "\t" trim(desc)
            next
        }
        # Pattern: "  -x   description"  (no long form)
        if (match(line, /^[ \t]*-[A-Za-z0-9][ \t][ \t]+/)) {
            head = substr(line, 1, RLENGTH)
            desc = substr(line, RLENGTH + 1)
            if (match(head, /-[A-Za-z0-9]/)) short = substr(head, RSTART, 2)
            print short "\t\t\t" trim(desc)
            next
        }
    }' | sort -u
}

# Render parsed options as a zsh _arguments completion.
# Stdin: TSV from parse_options. Args: cmd_name
render_completion() {
    local cmd="$1"
    printf '#compdef %s\n\n' "$cmd"
    printf '# Auto-generated by zsh-complete generic.sh -- do not edit.\n\n'
    printf '_%s() {\n  _arguments \\\n' "$cmd"

    local first=1 short long arg desc spec
    while IFS=$'\t' read -r short long arg desc; do
        [[ -z "$short$long" ]] && continue
        # Escape brackets and single-quotes for _arguments specs
        desc=${desc//\'/\'\\\'\'}
        desc=${desc//[/\\[}
        desc=${desc//]/\\]}
        if [[ -n "$short" && -n "$long" ]]; then
            spec="{$short,$long}[$desc]"
        elif [[ -n "$long" ]]; then
            spec="$long[$desc]"
        else
            spec="$short[$desc]"
        fi
        if [[ -n "$arg" ]]; then
            spec="${spec}:${arg}: "
        fi
        if [[ $first -eq 1 ]]; then
            printf "    '%s'" "$spec"
            first=0
        else
            printf " \\\\\n    '%s'" "$spec"
        fi
    done
    printf '\n}\n\n_%s "$@"\n' "$cmd"
}

generate_for_command() {
    local cmd="$1" help_source="$2" stdout_only="$3"

    local help_text
    if [[ -n "$help_source" ]]; then
        help_text=$(<"$help_source")
    else
        if ! help_text=$(get_help_text "$cmd"); then
            log_error "No help available for $cmd"
            return 1
        fi
    fi

    local parsed
    parsed=$(echo "$help_text" | strip_ansi | parse_options)
    if [[ -z "$parsed" ]]; then
        log_warn "No options parsed for $cmd"
        return 1
    fi

    local rendered
    rendered=$(echo "$parsed" | render_completion "$cmd")

    if [[ "$stdout_only" == "true" ]]; then
        printf '%s\n' "$rendered"
        return 0
    fi

    local dir out lines
    dir="$(get_dir src)/generic/generic"
    ensure_dir "$dir"
    out="$dir/_$cmd"
    printf '%s\n' "$rendered" > "$out"
    lines=$(count_lines "$out")
    log_info "Generated $out ($lines lines)"

    local generic_file updated
    generic_file=$(get_file generic)
    ensure_dir "$(dirname "$generic_file")"
    [[ -f "$generic_file" ]] || echo '{}' > "$generic_file"
    updated=$(jq --arg c "$cmd" --arg p "$out" --argjson l "$lines" \
        '.[$c] = {path:$p, lines:$l, source:"generic"}' "$generic_file")
    printf '%s\n' "$updated" > "$generic_file"
}

main() {
    local help_source="" stdout_only="false" cmd=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --source) help_source="$2"; shift 2 ;;
            --stdout) stdout_only="true"; shift ;;
            -h|--help) show_help; exit 0 ;;
            -*) log_error "Unknown option: $1"; show_help; exit 1 ;;
            *) cmd="$1"; shift ;;
        esac
    done

    [[ -z "$cmd" ]] && { show_help; exit 1; }

    if [[ "$stdout_only" != "true" ]]; then
        load_config
    fi
    generate_for_command "$cmd" "$help_source" "$stdout_only"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
